# 🌮 Notebook 1 — Pandas: DataFrames y Series
### Unidad 2 | Python para Ciencia de Datos | UADE
#### Dataset: Top Tacos in San Diego 🏄

> 📚 Basado en **Python for Data Analysis, 3rd Ed.** — Wes McKinney, Cap. 5  
> Libro disponible en: https://wesmckinney.com/book/pandas-basics

---

**pandas** es la librería central para el análisis de datos tabulares en Python.  
En este notebook vamos a explorar sus estructuras fundamentales usando un dataset real: los mejores taquerías de San Diego, California. 🌮

In [3]:
import pandas as pd
import numpy as np
print(f'pandas version: {pd.__version__}')

pandas version: 2.3.1

---
## 1. Series — la estructura unidimensional

Una **Series** es un array unidimensional con un índice etiquetado:

In [7]:
lista = [4.6, 4.7, 4.8, 4.3, 4.7]
lista[2]

4.8

In [13]:
scores = pd.Series([4.6, 4.7, 4.8, 4.3, 4.7], index=["s1", "s2", "s3","s4","s5"])
scores["s3"]

np.float64(4.8)

In [14]:
# Series desde una lista
scores = pd.Series([4.6, 4.7, 4.8, 4.3, 4.7],
                   index=["El Gordo", "The Taco Stand", "Las Cuatro Milpas",
                          "Lucha Libre", "Oscars Seafood"],
                   name="score")
print(scores)
print("\ndtype:", scores.dtype)
print("índice:", scores.index.tolist())

El Gordo             4.6
The Taco Stand       4.7
Las Cuatro Milpas    4.8
Lucha Libre          4.3
Oscars Seafood       4.7
Name: score, dtype: float64

dtype: float64
índice: ['El Gordo', 'The Taco Stand', 'Las Cuatro Milpas', 'Lucha Libre', 'Oscars Seafood']

In [15]:
# Acceso por etiqueta y por posición
print("El Gordo:", scores["El Gordo"])
print("Top 3:\n", scores[:3])

# Operaciones vectorizadas (igual que NumPy)
print("\nScores + 0.1:\n", scores + 0.1)
print("\nRestaurantes con score >= 4.7:\n", scores[scores >= 4.7])

El Gordo: 4.6
Top 3:
 El Gordo             4.6
The Taco Stand       4.7
Las Cuatro Milpas    4.8
Name: score, dtype: float64

Scores + 0.1:
 El Gordo             4.7
The Taco Stand       4.8
Las Cuatro Milpas    4.9
Lucha Libre          4.4
Oscars Seafood       4.8
Name: score, dtype: float64

Restaurantes con score >= 4.7:
 The Taco Stand       4.7
Las Cuatro Milpas    4.8
Oscars Seafood       4.7
Name: score, dtype: float64

---
## 2. DataFrame — la estructura tabular

Un **DataFrame** es una tabla de datos con filas y columnas etiquetadas.  
Vamos a crearlo desde la lista de diccionarios del dataset de tacos:

In [4]:
# El dataset completo viene de una lista de diccionarios
# (generada a partir del Excel top_tacos_in_san_diego.xlsx)
tacos_list = [
  {
    "ID": "SDT-001",
    "Restaurant Name": "Tacos El Gordo",
    "Score": 4.6,
    "Latitude": 32.6305,
    "Longitude": -117.0601,
    "Review Snippet": "The adobada is non-negotiable. Authenticity at its peak."
  },
  {
    "ID": "SDT-002",
    "Restaurant Name": "The Taco Stand",
    "Score": 4.7,
    "Latitude": 32.8427,
    "Longitude": -117.2731,
    "Review Snippet": "Handmade tortillas make the Al Pastor truly stand out."
  },
  {
    "ID": "SDT-003",
    "Restaurant Name": "Las Cuatro Milpas",
    "Score": 4.8,
    "Latitude": 32.7003,
    "Longitude": -117.1431,
    "Review Snippet": "Old school charm with the best chorizo in Barrio Logan."
  },
  {
    "ID": "SDT-004",
    "Restaurant Name": "Lucha Libre Taco Shop",
    "Score": 4.3,
    "Latitude": 32.7441,
    "Longitude": -117.1724,
    "Review Snippet": "Get the Undefeated Taco; the salsa bar is top-tier."
  }
]

# Convertir lista de diccionarios a DataFrame
df = pd.DataFrame(tacos_list)
print("Tipo:", type(df))
print("Shape:", df.shape)   # (filas, columnas)
df

Tipo: <class 'pandas.core.frame.DataFrame'>
Shape: (4, 6)

,ID,Restaurant Name,Score,Latitude,Longitude,Review Snippet
0,SDT-001,Tacos El Gordo,4.6,32.6305,-117.0601,The adobada is non-negotiable. Authenticity at...
1,SDT-002,The Taco Stand,4.7,32.8427,-117.2731,Handmade tortillas make the Al Pastor truly st...
2,SDT-003,Las Cuatro Milpas,4.8,32.7003,-117.1431,Old school charm with the best chorizo in Barr...
3,SDT-004,Lucha Libre Taco Shop,4.3,32.7441,-117.1724,Get the Undefeated Taco; the salsa bar is top-...

---
## 3. Exploración inicial del DataFrame

Los primeros comandos que ejecutamos al recibir un nuevo dataset:

In [5]:
# .info() — tipos de datos, valores nulos, memoria
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               4 non-null      object
 1   Restaurant Name  4 non-null      object
 2   Score            4 non-null      float64
 3   Latitude         4 non-null      float64
 4   Longitude        4 non-null      float64
 5   Review Snippet   4 non-null      object
dtypes: float64(3), object(3)
memory usage: 324.0+ bytes

In [6]:
# .head() y .tail() — primeras y últimas filas
print('--- head(3) ---')
print(df.head())
print('\n--- tail(3) ---')
print(df.tail(3))

--- head(3) ---
        ID        Restaurant Name  Score  Latitude  Longitude  \
0  SDT-001         Tacos El Gordo    4.6   32.6305  -117.0601
1  SDT-002         The Taco Stand    4.7   32.8427  -117.2731
2  SDT-003      Las Cuatro Milpas    4.8   32.7003  -117.1431
3  SDT-004  Lucha Libre Taco Shop    4.3   32.7441  -117.1724

                                      Review Snippet
0  The adobada is non-negotiable. Authenticity at...
1  Handmade tortillas make the Al Pastor truly st...
2  Old school charm with the best chorizo in Barr...
3  Get the Undefeated Taco; the salsa bar is top-...

--- tail(3) ---
        ID        Restaurant Name  Score  Latitude  Longitude  \
1  SDT-002         The Taco Stand    4.7   32.8427  -117.2731
2  SDT-003      Las Cuatro Milpas    4.8   32.7003  -117.1431
3  SDT-004  Lucha Libre Taco Shop    4.3   32.7441  -117.1724

                                      Review Snippet
1  Handmade tortillas make the Al Pastor truly st...
2  Old school charm with the best chorizo in Barr...
3  Get the Undefeated Taco; the salsa bar is top-...

In [16]:
# .sample() — muestra aleatoria (útil para exploración rápida)
df.sample(2, random_state=42)

,ID,Restaurant Name,Score,Latitude,Longitude,Review Snippet
1,SDT-002,The Taco Stand,4.7,32.8427,-117.2731,Handmade tortillas make the Al Pastor truly st...
3,SDT-004,Lucha Libre Taco Shop,4.3,32.7441,-117.1724,Get the Undefeated Taco; the salsa bar is top-...

In [18]:
# .describe() — estadísticas descriptivas de columnas numéricas
df.describe(include="object")

,ID,Restaurant Name,Review Snippet
count,4,4,4
unique,4,4,4
top,SDT-001,Tacos El Gordo,The adobada is non-negotiable. Authenticity at...
freq,1,1,1

In [19]:
# .dtypes — tipo de dato de cada columna
df.dtypes

ID                  object
Restaurant Name     object
Score              float64
Latitude           float64
Longitude          float64
Review Snippet      object
dtype: object

---
## 4. Selección de datos

In [ ]:
# Seleccionar una columna → Series
print(df["Restaurant Name"].head())
print("\nTipo:", type(df["Restaurant Name"]))

In [ ]:
# Seleccionar múltiples columnas → DataFrame
df[["Restaurant Name", "Score"]].head()

In [ ]:
# .loc[] — selección por etiqueta de índice
print(df.loc[0:2, ["Restaurant Name", "Score"]])

In [ ]:
# .iloc[] — selección por posición numérica
print(df.iloc[0:3, 0:3])

---
## 5. Filtrado y consultas

In [ ]:
# Filtrar restaurantes con score mayor o igual a 4.7
top_rated = df[df["Score"] >= 4.7]
print(f"Restaurantes con score >= 4.7: {len(top_rated)}")
top_rated[["Restaurant Name", "Score"]].sort_values("Score", ascending=False)

In [ ]:
# Múltiples condiciones: score alto Y latitud al norte de San Diego centro
norte_y_top = df[(df["Score"] >= 4.6) & (df["Latitude"] > 32.78)]
norte_y_top[["Restaurant Name", "Score", "Latitude"]]

---
## 6. Operaciones sobre columnas

In [ ]:
# Crear una nueva columna: Score redondeado a entero (categoría)
df["Score_Category"] = df["Score"].apply(lambda x: "🌟 Excelente" if x >= 4.7 else "👍 Muy bueno")
df[["Restaurant Name", "Score", "Score_Category"]].head(8)

In [ ]:
# Estadísticas por grupo
print("Estadísticas por categoría:")
print(df.groupby("Score_Category")["Score"].agg(["count", "mean", "min", "max"]))

---
## 7. Ordenamiento

In [ ]:
# Ordenar por score descendente
df.sort_values("Score", ascending=False)[["Restaurant Name", "Score"]].head(10)

---
## 8. Exportación en múltiples formatos

In [21]:
import os
os.makedirs("/mnt/user-data/outputs", exist_ok=True)

# CSV
df.to_csv("/mnt/user-data/outputs/tacos_sd.csv", index=False)

# JSON
df.to_json("/mnt/user-data/outputs/tacos_sd.json", orient="records", indent=2, force_ascii=False)

# Excel
df.to_excel("/mnt/user-data/outputs/tacos_sd_export.xlsx", index=False)

print("Archivos exportados:")
print("  ✅ tacos_sd.csv")
print("  ✅ tacos_sd.json")
print("  ✅ tacos_sd_export.xlsx")

ModuleNotFoundError: No module named 'openpyxl'

---
## 9. Visualización rápida con pandas

Pandas integra matplotlib para visualizaciones directas:

In [ ]:
import matplotlib.pyplot as plt

# Distribución de scores
df["Score"].value_counts().sort_index().plot(kind="bar", figsize=(8, 4), color="coral", edgecolor="black")
plt.title("Distribución de scores — Top Tacos San Diego")
plt.xlabel("Score")
plt.ylabel("Cantidad de restaurantes")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

---
## 🔑 Resumen de comandos explorados

| Comando | Descripción |
|---|---|
| `pd.DataFrame(lista_de_dicts)` | Crear DataFrame desde lista de diccionarios |
| `df.info()` | Tipos, nulos y memoria |
| `df.head(n)` | Primeras n filas |
| `df.tail(n)` | Últimas n filas |
| `df.sample(n)` | Muestra aleatoria |
| `df.describe()` | Estadísticas descriptivas |
| `df["columna"]` | Seleccionar una columna (Series) |
| `df[["col1", "col2"]]` | Seleccionar varias columnas |
| `df.loc[filas, cols]` | Selección por etiqueta |
| `df.iloc[filas, cols]` | Selección por posición |
| `df[condicion]` | Filtrado booleano |
| `df.sort_values("col")` | Ordenar por columna |
| `df.groupby("col").agg()` | Agrupar y agregar |
| `df.to_csv() / to_json() / to_excel()` | Exportar |