# Introducción a Merge con Pandas

En este notebook vamos a aprender cómo combinar datasets usando distintos tipos de joins.

<img src="https://www.red-gate.com/simple-talk/wp-content/uploads/2025/09/Full-Outer-Join-featured-image-scaled.jpg" width="600">

In [1]:
import pandas as pd

## Creamos los datasets

In [11]:
fact_chart = pd.DataFrame({
    "song_id": [1, 2, 3, 4, 5, 6, 7, 8, 9],
    "chart_id": [101, 101, 102, 102, 103, 103, 104, 104, 105],
    "highest_charting_position": [1, 5, 10, 3, 8, 2, 7, 4, 6],
    "streams": [500000, 300000, 150000, 400000, 250000, 450000, 200000, 350000, 100000],
    "artist_followers": [1000000, 800000, 500000, 1200000, 600000, 1100000, 700000, 900000, 400000]
})

fact_chart.shape

(9, 5)

In [12]:
dim_songs = pd.DataFrame({
    "song_id": [1, 2, 3, 4, 5, 10, 11, 12],
    "song_name": ["Song A", "Song B", "Song C", "Song D", "Song E", "Song X", "Song Y", "Song Z"],
    "artist": ["Artist 1", "Artist 2", "Artist 3", "Artist 4", "Artist 5", "Artist X", "Artist Y", "Artist Z"],
    "genre": ["Pop", "Rock", "Hip-Hop", "Pop", "Jazz", "Electronic", "Pop", "Rock"],
    "release_date": pd.to_datetime([
        "2020-01-01", "2020-02-01", "2020-03-01", "2020-04-01",
        "2020-05-01", "2021-01-01", "2021-02-01", "2021-03-01"
    ])
})

dim_songs.shape

(8, 5)

## INNER JOIN

In [8]:
df_inner_join = pd.merge(fact_chart, dim_songs, on="song_id", how="inner")
df_inner_join.shape

(5, 9)

In [13]:
df_inner_join.sort_values(by="song_id")

,song_id,chart_id,highest_charting_position,streams,artist_followers,song_name,artist,genre,release_date
0,1,101,1,500000,1000000,Song A,Artist 1,Pop,2020-01-01
1,2,101,5,300000,800000,Song B,Artist 2,Rock,2020-02-01
2,3,102,10,150000,500000,Song C,Artist 3,Hip-Hop,2020-03-01
3,4,102,3,400000,1200000,Song D,Artist 4,Pop,2020-04-01
4,5,103,8,250000,600000,Song E,Artist 5,Jazz,2020-05-01

## LEFT JOIN

In [15]:
df_left_join = pd.merge(fact_chart, dim_songs, on="song_id", how="left")
df_left_join.shape

(9, 9)

In [16]:
df_left_join.sort_values(by="song_id")

,song_id,chart_id,highest_charting_position,streams,artist_followers,song_name,artist,genre,release_date
0,1,101,1,500000,1000000,Song A,Artist 1,Pop,2020-01-01
1,2,101,5,300000,800000,Song B,Artist 2,Rock,2020-02-01
2,3,102,10,150000,500000,Song C,Artist 3,Hip-Hop,2020-03-01
3,4,102,3,400000,1200000,Song D,Artist 4,Pop,2020-04-01
4,5,103,8,250000,600000,Song E,Artist 5,Jazz,2020-05-01
5,6,103,2,450000,1100000,NaN,NaN,NaN,NaT
6,7,104,7,200000,700000,NaN,NaN,NaN,NaT
7,8,104,4,350000,900000,NaN,NaN,NaN,NaT
8,9,105,6,100000,400000,NaN,NaN,NaN,NaT

## RIGHT JOIN

In [17]:
df_right_join = pd.merge(fact_chart, dim_songs, on="song_id", how="right")
df_right_join.shape

(8, 9)

In [18]:
df_right_join

,song_id,chart_id,highest_charting_position,streams,artist_followers,song_name,artist,genre,release_date
0,1,101.0,1.0,500000.0,1000000.0,Song A,Artist 1,Pop,2020-01-01
1,2,101.0,5.0,300000.0,800000.0,Song B,Artist 2,Rock,2020-02-01
2,3,102.0,10.0,150000.0,500000.0,Song C,Artist 3,Hip-Hop,2020-03-01
3,4,102.0,3.0,400000.0,1200000.0,Song D,Artist 4,Pop,2020-04-01
4,5,103.0,8.0,250000.0,600000.0,Song E,Artist 5,Jazz,2020-05-01
5,10,NaN,NaN,NaN,NaN,Song X,Artist X,Electronic,2021-01-01
6,11,NaN,NaN,NaN,NaN,Song Y,Artist Y,Pop,2021-02-01
7,12,NaN,NaN,NaN,NaN,Song Z,Artist Z,Rock,2021-03-01

## FULL OUTER JOIN

* Vemos los datasets combinados
* NaN donde no hay match
* Pero no sabemos fácilmente de dónde vino cada fila

In [19]:
df_outer_join = pd.merge(fact_chart, dim_songs, on="song_id", how="outer")
df_outer_join.shape

(12, 9)

In [20]:
df_outer_join

,song_id,chart_id,highest_charting_position,streams,artist_followers,song_name,artist,genre,release_date
0,1,101.0,1.0,500000.0,1000000.0,Song A,Artist 1,Pop,2020-01-01
1,2,101.0,5.0,300000.0,800000.0,Song B,Artist 2,Rock,2020-02-01
2,3,102.0,10.0,150000.0,500000.0,Song C,Artist 3,Hip-Hop,2020-03-01
3,4,102.0,3.0,400000.0,1200000.0,Song D,Artist 4,Pop,2020-04-01
4,5,103.0,8.0,250000.0,600000.0,Song E,Artist 5,Jazz,2020-05-01
5,6,103.0,2.0,450000.0,1100000.0,NaN,NaN,NaN,NaT
6,7,104.0,7.0,200000.0,700000.0,NaN,NaN,NaN,NaT
7,8,104.0,4.0,350000.0,900000.0,NaN,NaN,NaN,NaT
8,9,105.0,6.0,100000.0,400000.0,NaN,NaN,NaN,NaT
9,10,NaN,NaN,NaN,NaN,Song X,Artist X,Electronic,2021-01-01
10,11,NaN,NaN,NaN,NaN,Song Y,Artist Y,Pop,2021-02-01
11,12,NaN,NaN,NaN,NaN,Song Z,Artist Z,Rock,2021-03-01

## Indicador de origen

* Vemos los datasets combinados
* NaN donde no hay match
* Se agrega una columna adicional, "_merge" que indica como se generó la fila

In [ ]:
pd.merge(fact_chart, dim_songs, on="song_id", how="outer", indicator=True)